import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatButtonToggleModule,
  MatStepperModule,
  MatExpansionModule,
  MatSlideToggleModule,
  MatRadioModule,
  MatTableModule,
  MatTabsModule,
  MatRippleModule,
  MatProgressSpinnerModule,
  MatTooltipModule,
  MatDialogModule,
  MatAutocompleteModule,
  MatBadgeModule,
  MatIconModule,
  MatSortModule,
  MatProgressBarModule,
  MatFormFieldModule,
  MatSelectModule,
  MatChipsModule,
  MatCardModule,
  MatPaginatorModule,
  MatInputModule,
  MatOptionModule,
  MatDividerModule,
  MatListModule,
  MatToolbarModule,
  MatSidenavModule,
  MatCheckboxModule,
  MatSnackBarModule,
} from '@angular/material';


@NgModule({
  imports: [

    MatButtonModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatToolbarModule,
    MatInputModule,
    MatAutocompleteModule,
    MatExpansionModule,
    MatChipsModule,
    MatSidenavModule,
    MatTabsModule,
    MatRadioModule,
    MatRippleModule,
    MatTooltipModule,
    MatCardModule,
    MatDialogModule,
    MatDividerModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatOptionModule,
    MatSortModule,
    MatBadgeModule,
    MatTableModule,
    MatCheckboxModule,
    MatIconModule,
    MatProgressBarModule,
    MatSlideToggleModule,
    MatFormFieldModule,
    MatSelectModule,
    MatListModule

  ],
  exports: [

    MatButtonModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatInputModule,
    MatRadioModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatSnackBarModule,
    MatTableModule,
    MatSlideToggleModule,
    MatCheckboxModule,
    MatDividerModule,
    MatSortModule,
    MatSidenavModule,
    MatBadgeModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatChipsModule,
    MatToolbarModule,
    MatRippleModule,
    MatTooltipModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatIconModule,
    MatOptionModule,
    MatProgressBarModule,
    MatFormFieldModule,
    MatSelectModule,
    MatCardModule,
    MatListModule,

  ],
})
export class MaterialModule { }
